export type GeminiEnrichmentResult = {
  provider: string
  latencyMs: number
  model: string
  summary: string
  category: string
  topics: string[]
  entities: Array<{ name: string; type: string; relevance?: string }>
  suggestedTags: string[]
  semanticKeywords: string[]
  crawlPriorityScore: number
  notice?: string
}

export async function enrichWithGemini(
  pageData: {
    url: string
    title: string
    description: string
    headings: string[]
    snippet: string
    domain: string
    language?: string
  },
  profileDirective?: string
): Promise<GeminiEnrichmentResult> {
  const startTime = Date.now()
  const apiKey = process.env.GEMINI_API_KEY

  if (apiKey && apiKey.trim().length > 0) {
    try {
      const prompt = `You are the backend AI metadata enrichment engine for the VOID Search Engine Crawler.
Analyze the following webpage extracted data and return a strictly structured JSON object.

Target Webpage Data:
- URL: ${pageData.url}
- Domain: ${pageData.domain}
- Title: ${pageData.title}
- Description: ${pageData.description}
- Key Headings: ${pageData.headings.slice(0, 8).join(' | ')}
- Content Snippet: ${pageData.snippet.slice(0, 1200)}
- Profile Directive: ${profileDirective || 'General Search Indexing'}

Your task:
1. Provide a natural, engaging search engine result snippet (1 to 2 sentences) describing the entity, person, company, or content directly for end users. Never start with "This page...", "This document...", "The associated metadata...", or mention crawling/directives. Write it as an informative search snippet (e.g. "Official profile of ... featuring ...").
2. Determine primary content category (e.g., Social Profile, Developer Documentation, Machine Learning Research, Tech Ecosystem, Security, Academic Literature, Product Manual, News & Editorial).
3. Identify 4 to 6 specific topics.
4. Extract 4 to 8 key named entities (technologies, organizations, prominent figures, specifications).
5. Suggest 6 to 10 high-value search query tags.
6. Suggest 5 semantic latent keywords.
7. Assign a crawl/index priority score between 1 and 100 based on information value and depth.

Respond with ONLY valid JSON with this exact schema:
{
  "summary": "...",
  "category": "...",
  "topics": ["topic1", "topic2", ...],
  "entities": [{"name": "...", "type": "Technology|Organization|Person|Concept"}],
  "suggestedTags": ["tag1", "tag2", ...],
  "semanticKeywords": ["kw1", "kw2", ...],
  "crawlPriorityScore": 88
}`

      const candidateModels = ['gemini-2.5-flash-lite', 'gemini-3.6-flash', 'gemini-flash-latest']
      for (const modelId of candidateModels) {
        try {
          const response = await fetch(
            `https://generativelanguage.googleapis.com/v1beta/models/${modelId}:generateContent?key=${apiKey}`,
            {
              method: 'POST',
              headers: {
                'Content-Type': 'application/json',
              },
              body: JSON.stringify({
                contents: [
                  {
                    role: 'user',
                    parts: [{ text: prompt }],
                  },
                ],
                generationConfig: {
                  responseMimeType: 'application/json',
                  temperature: 0.2,
                  maxOutputTokens: 2048,
                },
              }),
            }
          )

          if (response.ok) {
            const json = await response.json()
            let text = json.candidates?.[0]?.content?.parts?.[0]?.text
            if (text) {
              text = text.replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/i, '').trim()
              const parsed = JSON.parse(text)
              return {
                provider: 'gemini-1.5-flash',
                latencyMs: Date.now() - startTime,
                model: modelId,
                summary: parsed.summary || 'Summary generated by Gemini.',
                category: parsed.category || 'Technology',
                topics: Array.isArray(parsed.topics) ? parsed.topics : [],
                entities: Array.isArray(parsed.entities) ? parsed.entities : [],
                suggestedTags: Array.isArray(parsed.suggestedTags) ? parsed.suggestedTags : [],
                semanticKeywords: Array.isArray(parsed.semanticKeywords) ? parsed.semanticKeywords : [],
                crawlPriorityScore: typeof parsed.crawlPriorityScore === 'number' ? parsed.crawlPriorityScore : 82,
              }
            }
          }
        } catch {
          // Continue to next candidate model
        }
      }
    } catch (err) {
      console.error('Gemini API request failed:', err)
    }
  }

  // Clean fallback without mock or fabricated entities
  const isSocial = ['instagram.com', 'facebook.com', 'linkedin.com', 'twitter.com', 'x.com', 'threads.net', 'tiktok.com'].some(
    (d) => pageData.domain === d || pageData.domain.endsWith('.' + d)
  )

  let fallbackCategory = 'General Web Resource'
  let fallbackTopics: string[] = []

  if (isSocial) {
    fallbackCategory = 'Social Profile'
    const platform = pageData.domain.replace(/\.(com|org|net)$/i, '')
    const platformTitle = platform.charAt(0).toUpperCase() + platform.slice(1)
    const cleanTitle = (pageData.title || '').replace(/\s*[•|–-].*$/, '').trim()
    fallbackTopics = [`${platformTitle} Profile`, 'Social Media', cleanTitle || 'Profile'].filter(Boolean)
  } else {
    // Only take headings that aren't developer boilerplate
    const validHeadings = (pageData.headings || []).filter(
      (h) => !['Core Concepts and Architecture', 'Quick Reference & Examples', 'API Specifications'].includes(h)
    )
    fallbackTopics = validHeadings.slice(0, 4)
    if (fallbackTopics.length === 0) {
      if (pageData.title) fallbackTopics.push(pageData.title)
      if (pageData.domain) fallbackTopics.push(pageData.domain)
    }
  }

  let fallbackSummary = pageData.description ? pageData.description.trim() : `Document from ${pageData.domain} extracted by crawler.`
  if (isSocial && pageData.domain.includes('instagram.com')) {
    const userMatch = pageData.url.match(/instagram\.com\/([a-zA-Z0-9_.]+)/)
    const handle = userMatch ? `@${userMatch[1]}` : ''
    fallbackSummary = `${handle ? `${handle} on ` : ''}Instagram: Photos, videos, updates, and profile details.`
  }

  return {
    provider: 'gemini',
    latencyMs: Date.now() - startTime,
    model: 'gemini-3.6-flash',
    summary: fallbackSummary,
    category: fallbackCategory,
    topics: fallbackTopics,
    entities: [],
    suggestedTags: [],
    semanticKeywords: [],
    crawlPriorityScore: 50,
    notice: 'Gemini API call did not complete. Configure GEMINI_API_KEY for live AI enrichment.',
  }
}

